apiVersion: v1
kind: Service
metadata:
  name: stable-service
spec:
  selector:
    app: canary-demo
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  selector:
    app: canary-demo
  ports:
  - port: 80
    targetPort: 5000